apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-rolebinding
subjects:
- kind: Group
  name: github-actions
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io